### PR TITLE
Recognize Koert for his contributions as an author

### PR DESCRIPTION
**Pull request by jmcclell**
@kvdveer  I'm 80% sure this syntax is kosher with pypi but haven't tested it. Perhaps as you prep the next release you can pull this in and see if it blows up in your face? :)

### CODE REVIEW

**Comment by kvdveer** [comment]
AFAIK, setuptools does not support multiple authors: http://legacy.python.org/dev/peps/pep-0345/#author-optional

You could use maintainer as a second author (which would actually be somewhat accurate), but that's not very future proof.

**Comment by jmcclell** [comment]
From what I understand, the "author" field is a free field. It's only author_email that is validated and must be a single, valid email address.

```
Author (optional)

A string containing the author's name at a minimum; additional contact information may be provided.

Example:

Author: C. Schultz, Universal Features Syndicate,
        Los Angeles, CA <cschultz@peanuts.example.com>
Author-email (optional)

A string containing the author's e-mail address. It can contain a name and e-mail address in the legal forms for a RFC-822 From: header.

Example:

Author-email: "C. Schultz" <cschultz@example.com>
```

**Comment by kvdveer** [comment]
Now that you explain it, I read it the same way. Given that it is so free
form, it will probably not break anything.

**Comment by jmcclell** [comment]
👍

**Pull request closed without merging**
