### PR TITLE
fixed context.current_app in Django 1.10

### PR DESCRIPTION
**Pull request by adilkhash**
Hi.
Fixed context.current_app AttributeError exception in Django 1.10 due to removal of current_app attribute from RequestContext object. See [release notes](https://docs.djangoproject.com/en/dev/releases/1.10/)

### CODE REVIEW

**Comment by camilonova** [comment]
@jmcclell please merge this one

**Comment by beaugunderson** [comment]
This PR fixes the issue I had. ✨

**Comment by jmcclell** [comment]
@kvdveer Thoughts? I don't have enough context at hand to know what the issue is (sorry guys, haven't been using Django for a few versions) so can't tell if this fix makes sense or not. It *seems* good to me..

**Comment by jmduke** [comment]
This also fixed the issue I had.

**Comment by camilonova** [comment]
@jmcclell The package does not work with latest django release without this. Please merge it and release a new version.

**Comment by beaugunderson** [comment]
@jmcclell i have to pitch transferring or sharing maintainership with [jazzband](https://jazzband.co/) one final time; they've been great about adding tests for multiple django versions in my experience :)

**Pull request merged**
